// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-X3Z7zQ3gBylT3Q7OCwwQT-ivWGP7ktQ',
    appId: '1:230409103297:web:d5f77daa19cab33a67b140',
    messagingSenderId: '230409103297',
    projectId: 'apptccecclesia',
    authDomain: 'apptccecclesia.firebaseapp.com',
    storageBucket: 'apptccecclesia.firebasestorage.app',
    measurementId: 'G-W8DKGGB2T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQFVX0zfUZqk67ajkiEf3hyV68ZEkIPSk',
    appId: '1:230409103297:android:91ddb65deac1e7e367b140',
    messagingSenderId: '230409103297',
    projectId: 'apptccecclesia',
    storageBucket: 'apptccecclesia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWaIHq94XS8Nyz5Yi30XGEtIjBesIbE58',
    appId: '1:230409103297:ios:80b3484a5aa3995467b140',
    messagingSenderId: '230409103297',
    projectId: 'apptccecclesia',
    storageBucket: 'apptccecclesia.firebasestorage.app',
    iosBundleId: 'com.example.appTcc',
  );
}
